# Travic-CI-Config file for authLdap
#
language: php

addons:
  apt:
    packages:
    - slapd
    - ldap-utils

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

stages:
  - check
  - test

jobs:
  fast_finish: true
  include:
  - stage: check
    php:  7.4
    script: ./vendor/bin/phpcs --standard=PSR2 ldap.php authLdap.php src/ tests/
    before_script:
    - composer self-update
    - composer update --prefer-source
    after_script: skip
  - stage: test
  allow_failures:
  - php: nightly
  - php: 8.0

before_script:
 - .ci/OpenLDAP_run.sh
 - .ci/load_fixtures.sh
 - ./.travis.install.sh
 - composer dumpautoload

script:
- ./vendor/bin/phpunit --configuration=phpunit.travis.xml

after_script:
- ./.travis.after.sh

