# Travic-CI-Config file for authLdap
#
language: php

addons:
  apt:
    packages:
    - slapd
    - ldap-utils

matrix:
  fast_finish: true
  include:
  - php: 7.2
  - php: 7.3
  - php: 7.4
  - php: nightly
  allow_failures:
  - php: nightly

before_script:
 - ./.travis.install.sh
 - phpenv config-add .ci/php.ini || return 0
 - .ci/OpenLDAP_run.sh
 - .ci/load_fixtures.sh
 - composer dumpautoload

script:
# - ./vendor/bin/phpcs --standard=PSR2 ldap.php authLdap.php tests/
- ./vendor/bin/phpunit --configuration=phpunit.travis.xml

after_script:
- ./.travis.after.sh

